### ISSUE TITLE
Mutualisation avec french_locator_filter

### ISSUE THREAD

**Issue by vpicavet** [Gui0delp/french_address#1]
Hello,

On avait déjà développé un plugin pour la barre locator en intégrant adresse.gouv.fr.
https://github.com/Oslandia/french_locator_filter/issues/new

Ce serait bien de se synchroniser pour mutualiser les efforts et ne pas dupliquer les plugins QGIS je pense.

Ping @haubourg

**Comment by haubourg** [comment]
+1 on serait très preneur d'une PR pour enrichir french_locator avec la partie récupération d'adresse en cliquant sur la carte. 
On pourrait aussi verser ce plugin au groupe QGIS utilisateur francophone pour tâcher de mutualiser en se concertant en amont.

**Comment by haubourg** [comment]
preneurs*

**Comment by Gui0delp** [comment]
Hello,

Effectivement, c'est maladroit de ma part, je m’en excuse. Je vais regarder la proposition de @haubourg . Est-il possible de se concerter, pour peut-être, envisager cette implémentation ?
